package de.noob.noobservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-16T15:40:02.643+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "NoobOnlineServiceBeanService", 
                  wsdlLocation = "http://localhost:8080/noob/NoobOnlineServiceBean?wsdl",
                  targetNamespace = "http://noobservice.noob.de/") 
public class NoobOnlineServiceBeanService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://noobservice.noob.de/", "NoobOnlineServiceBeanService");
    public final static QName NoobOnlineServiceBeanPort = new QName("http://noobservice.noob.de/", "NoobOnlineServiceBeanPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/noob/NoobOnlineServiceBean?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NoobOnlineServiceBeanService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/noob/NoobOnlineServiceBean?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NoobOnlineServiceBeanService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NoobOnlineServiceBeanService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoobOnlineServiceBeanService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NoobOnlineServiceBeanService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NoobOnlineServiceBeanService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NoobOnlineServiceBeanService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NoobOnlineServiceBean
     */
    @WebEndpoint(name = "NoobOnlineServiceBeanPort")
    public NoobOnlineServiceBean getNoobOnlineServiceBeanPort() {
        return super.getPort(NoobOnlineServiceBeanPort, NoobOnlineServiceBean.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoobOnlineServiceBean
     */
    @WebEndpoint(name = "NoobOnlineServiceBeanPort")
    public NoobOnlineServiceBean getNoobOnlineServiceBeanPort(WebServiceFeature... features) {
        return super.getPort(NoobOnlineServiceBeanPort, NoobOnlineServiceBean.class, features);
    }

}
