package de.noob.noobservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-06-16T15:40:02.562+02:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://noobservice.noob.de/", name = "NoobOnlineServiceBean")
@XmlSeeAlso({ObjectFactory.class})
public interface NoobOnlineServiceBean {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.DeleteUser")
    @WebMethod
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.DeleteUserResponse")
    public de.noob.noobservice.ReturnCodeResponse deleteUser(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLocationDetails", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GetLocationDetails")
    @WebMethod
    @ResponseWrapper(localName = "getLocationDetailsResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GetLocationDetailsResponse")
    public de.noob.noobservice.LocationTO getLocationDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logout", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.Logout")
    @WebMethod
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.LogoutResponse")
    public de.noob.noobservice.ReturnCodeResponse logout(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "commentOnLocation", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CommentOnLocation")
    @WebMethod
    @ResponseWrapper(localName = "commentOnLocationResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CommentOnLocationResponse")
    public de.noob.noobservice.ReturnCodeResponse commentOnLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "giveRating", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GiveRating")
    @WebMethod
    @ResponseWrapper(localName = "giveRatingResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GiveRatingResponse")
    public de.noob.noobservice.ReturnCodeResponse giveRating(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listCities", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListCities")
    @WebMethod
    @ResponseWrapper(localName = "listCitiesResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListCitiesResponse")
    public de.noob.noobservice.CityListResponse listCities();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.Register")
    @WebMethod
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.RegisterResponse")
    public de.noob.noobservice.ReturnCodeResponse register(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createLocation", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CreateLocation")
    @WebMethod
    @ResponseWrapper(localName = "createLocationResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CreateLocationResponse")
    public de.noob.noobservice.ReturnCodeResponse createLocation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetails", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailsResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.GetUserDetailsResponse")
    public de.noob.noobservice.UserTO getUserDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listLocationsWithName", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListLocationsWithName")
    @WebMethod
    @ResponseWrapper(localName = "listLocationsWithNameResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListLocationsWithNameResponse")
    public de.noob.noobservice.LocationListResponse listLocationsWithName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listLocationsWithCategory", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListLocationsWithCategory")
    @WebMethod
    @ResponseWrapper(localName = "listLocationsWithCategoryResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListLocationsWithCategoryResponse")
    public de.noob.noobservice.LocationListResponse listLocationsWithCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setLocationDetails", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.SetLocationDetails")
    @WebMethod
    @ResponseWrapper(localName = "setLocationDetailsResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.SetLocationDetailsResponse")
    public de.noob.noobservice.ReturnCodeResponse setLocationDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        de.noob.noobservice.LocationTO arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listAllLocations", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListAllLocations")
    @WebMethod
    @ResponseWrapper(localName = "listAllLocationsResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListAllLocationsResponse")
    public de.noob.noobservice.LocationListResponse listAllLocations(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "createLocationWithImage", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CreateLocationWithImage")
    @WebMethod
    @ResponseWrapper(localName = "createLocationWithImageResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.CreateLocationWithImageResponse")
    public de.noob.noobservice.ReturnCodeResponse createLocationWithImage(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        int arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.lang.String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        byte[] arg8
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.Login")
    @WebMethod
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.LoginResponse")
    public de.noob.noobservice.UserLoginResponse login(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "setUserDetails", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.SetUserDetails")
    @WebMethod
    @ResponseWrapper(localName = "setUserDetailsResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.SetUserDetailsResponse")
    public de.noob.noobservice.ReturnCodeResponse setUserDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "listCategories", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListCategories")
    @WebMethod
    @ResponseWrapper(localName = "listCategoriesResponse", targetNamespace = "http://noobservice.noob.de/", className = "de.noob.noobservice.ListCategoriesResponse")
    public de.noob.noobservice.CategoryListResponse listCategories();
}
